# my_string = input('ваше имя: ' )
print('ваше имя'.upper())
print('ваше имя'.lower())
print('ваше имя'.replace(' ', ''))
print('ваше имя'.replace('аше имя', ''))
print('ваше имя'.replace('ваше им', ''))